# Generated by Django 4.2.16 on 2024-10-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_picture', models.ImageField(upload_to='uploads/')),
                ('car_type', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('car_system', models.CharField(blank=True, default='', max_length=255)),
                ('car_seat', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
