# Generated by Django 4.2.16 on 2024-10-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_system',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
