# Generated by Django 4.2.16 on 2024-10-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0005_alter_car_car_system_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
