# Generated by Django 4.2.16 on 2024-10-29 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0010_remove_car_uploaded_at_car_car_seat_car_car_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=255)),
                ('startDateTime', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 21, 16, 1, 358404, tzinfo=datetime.timezone.utc), null=True)),
                ('endDateTime', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 21, 16, 1, 358404, tzinfo=datetime.timezone.utc), null=True)),
                ('descript', models.TextField(blank=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booksys.car')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
