# Generated by Django 4.2.16 on 2024-10-29 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0011_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.AlterField(
            model_name='booking',
            name='endDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 21, 25, 38, 160531, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 21, 25, 38, 160531, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
