# Generated by Django 4.2.16 on 2024-10-29 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0012_remove_booking_car_alter_booking_enddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 21, 34, 47, 988783, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 21, 34, 47, 988783, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
