# Generated by Django 4.2.16 on 2024-10-29 23:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0013_alter_booking_enddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booksys.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 23, 17, 20, 549498, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 29, 23, 17, 20, 549498, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
