# Generated by Django 4.2.16 on 2024-10-30 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0014_booking_car_alter_booking_enddatetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='text',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 2, 0, 58, 633624, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 2, 0, 58, 633624, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
