# Generated by Django 4.2.16 on 2024-10-30 04:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0016_pdfupload_alter_booking_enddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booksys.pdfupload'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 4, 1, 10, 920759, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 4, 1, 10, 920759, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
