# Generated by Django 4.2.16 on 2024-10-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0014_alter_addphone_options_alter_addphone_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addphone',
            options={},
        ),
        migrations.AlterModelManagers(
            name='addphone',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='addphone',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='addphone',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addphone',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
