# Generated by Django 4.2.16 on 2024-10-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_alter_addphone_options_alter_addphone_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addphone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='addphone',
            name='username',
        ),
    ]
