# Generated by Django 4.2.16 on 2024-10-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0018_car_color_car_seat_car_type_car_carbooking_type_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbooking',
            name='seat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
