# Generated by Django 4.2.16 on 2024-10-20 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0019_carbooking_color_carbooking_seat_alter_car_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='startDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='admin',
            field=models.BooleanField(default=1, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userKey', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
