# Generated by Django 4.2.16 on 2024-10-20 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0020_car_enddatetime_car_startdatetime_uploadedfile_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='car',
            name='startDateTime',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='admin',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
