# Generated by Django 4.2.16 on 2024-10-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0022_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
