# Generated by Django 4.2.16 on 2024-10-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0023_remove_uploadedfile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
